# Usa una imagen base de Java 17
FROM openjdk:17-jdk-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el JAR generado por Maven o Gradle
COPY target/residuos_Patologicos-0.0.1.jar app.jar

# Expone el puerto donde escucha la aplicación (ajústalo según tu configuración)
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]